# Generated by Django 3.0 on 2020-03-31 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebartitle',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebartitle',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
