# Generated by Django 3.0 on 2020-03-31 10:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfounder',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
