# Generated by Django 3.0 on 2020-04-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_us', '0002_auto_20200331_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutfounder',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('IN', 'Hindi')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('IN', 'Hindi')], max_length=10, null=True),
        ),
    ]
