# Generated by Django 3.0.2 on 2020-02-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediaPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubelink',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
