# Generated by Django 3.0 on 2020-03-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediaPage', '0002_auto_20200210_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='internship',
        ),
    ]
