# Generated by Django 3.0 on 2020-04-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hindiblogsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expert',
            new_name='Expert1',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='HindiCategory',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='HindiPosts',
        ),
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='HindiSubcategory',
        ),
    ]
