# Generated by Django 3.0 on 2020-04-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0007_auto_20200331_1625'),
        ('hindiblogsite', '0002_auto_20200401_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hindiposts',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogsite.Expert'),
        ),
        migrations.DeleteModel(
            name='Expert1',
        ),
    ]
