# Generated by Django 3.0 on 2020-04-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindiblogsite', '0005_auto_20200406_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='hindiposts',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('IN', 'Hindi')], max_length=10, null=True),
        ),
    ]
