# Generated by Django 3.0 on 2020-04-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_sendemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendemail',
            options={'verbose_name': 'Send Email', 'verbose_name_plural': 'Send Email'},
        ),
    ]
