# Generated by Django 3.0 on 2020-04-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0007_auto_20200331_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='YoutubeLink',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
